### ISSUE TITLE
merge into yarn2nix repo

### ISSUE THREAD

**Issue by Profpatsch** [Profpatsch/yarn-lock#10]
Since the cabal universe started supporting project definitions, there is no real reason to keep this repo separate from yarn2nix anymore.

**Comment by Profpatsch** [comment]
cc @sternenseemann

**Comment by sternenseemann** [comment]
All for it! We can just subtree it in, archive this repo and make a hackage release 0.6.3.1 (or 0.6.4?) with updated upstream information.

**Comment by Profpatsch** [comment]
Done in https://github.com/Profpatsch/yarn2nix/pull/61
